@startuml

hide footbox
autonumber

participant Step
box "chunk model" #lightblue
participant MyBatisCursorItemReader
participant PointAddItemProcessor
participant MyBatisBatchItemWriter
end box
participant SpringValidator
participant ChunkErrorLoggingListener #Orange
database "member_info" as db

[->Step : execute()
activate Step
Step -> MyBatisCursorItemReader : open()
activate MyBatisCursorItemReader
MyBatisCursorItemReader -> db : select
activate db
loop until exhausted read data
    group Framework Transaction
        group Create chunk (items)
            note right of MyBatisCursorItemReader: Repeat until chunk size is reached
            Step -> MyBatisCursorItemReader : read()
            MyBatisCursorItemReader -> db : fetch
            db --> MyBatisCursorItemReader : result
            deactivate db
            MyBatisCursorItemReader --> Step : item
            deactivate MyBatisCursorItemReader
            Step -> PointAddItemProcessor : process(item)
            activate PointAddItemProcessor
            PointAddItemProcessor -> SpringValidator : validate()
            activate SpringValidator
            SpringValidator -> SpringValidator : validate
            activate SpringValidator
            note right of SpringValidator: If value is not valid, throws ValidationException
            deactivate SpringValidator
            deactivate SpringValidator
            PointAddItemProcessor -> PointAddItemProcessor : business logic
            PointAddItemProcessor --> Step : item
            deactivate PointAddItemProcessor
        end
        Step -> MyBatisBatchItemWriter : write(items)
        activate MyBatisBatchItemWriter
        MyBatisBatchItemWriter -X db : update
        deactivate MyBatisBatchItemWriter
    else  <font color="red">An exception occurs</font>
        Step [#red]-> db : <font color="red"><b>rollback</b></font>
    end
    Step -> ChunkErrorLoggingListener
    activate ChunkErrorLoggingListener #Orange
    ChunkErrorLoggingListener -> ChunkErrorLoggingListener
    activate ChunkErrorLoggingListener #Orange
    deactivate ChunkErrorLoggingListener
    deactivate ChunkErrorLoggingListener
end
Step-->[ : ExitStatus
deactivate Step

'Set styles such as format and color of each figure
skinparam Note {
  BackgroundColor #b7fab1
  BorderColor black
}

skinparam Class {
  BorderColor black
  ArrowColor black
}

skinparam Sequence {
  BorderColor black
  ActorBorderColor black
  ArrowColor black
  LifeLineBorderColor black
  BoxLineColor black
  ParticipantBorderColor black
}

skinparam componentStyle uml2

skinparam Component {
  BorderColor black
  ArrowColor black
}

skinparam Interface {
  BorderColor black
  ArrowColor black
}

@enduml
