= Macchinetta Batch Framework (2.x) Development Guideline

This guideline provides best practices to develop highly maintainable Batch applications using full stack framework focussing on Spring Framework, Spring Batch and MyBatis.

This guideline helps to proceed with the software development (mainly coding) smoothly.

[NOTE]
.Stable guidelines
====
**GitHub contents is under construction**. Stable guidelines refer tohttps://macchinetta.github.io/batch-guideline/current/ja/[here].
====

== How to contribute

**Contributing (bug report, pull request, any comments etc.) is welcome !!** Please see the link:CONTRIBUTING.adoc[contributing guideline] for details.

== Source files

Source files of this guideline are stored into following directories.

* Japanese version : ``{repository root}/src/main/asciidoc/ja/``
* English version  : ``{repository root}/src/main/asciidoc/en/``

== Source file format

This guideline is written by the Asciidoctor format(``.adoc``).
About the Asciidoctor format, refer to the http://asciidoctor.org/docs/[Asciidoctor documentation contents].

== How to build

We build to HTML and PDF files using the https://github.com/asciidoctor/asciidoctor-maven-plugin[Asciidoctor Maven Plugin].

=== Clone a repository

Please clone a ``Macchinetta/batch-guideline`` repository or forked your repository.

[source, text]
----
$ git clone https://github.com/Macchinetta/batch-guideline.git
----

or

[source, text]
----
$ git clone https://github.com/{your account}/batch-guideline.git
----

=== Build HTML and PDF files for the Japanese

Please execute the two ``mvn`` command.
If build is successful, HTML files generate to the directory below.

* HTML : ``{your repository}/target/generated-docs/html``
* PDF  : ``{your repository}/target/generated-docs/pdf``

[source, text]
----
$ mvn -f image_pom.xml
$ mvn
----

=== Build HTML and PDF files for the English

Please execute the two ``mvn`` command with profile specification.
If build is successful, HTML files generate to the directory below.

* HTML : ``{your repository}/target/generated-docs/html``
* PDF  : ``{your repository}/target/generated-docs/pdf``

[source, text]
----
$ mvn -f image_pom.xml
$ mvn -P en
----

== Terms of use

Terms of use refer to link:/src/main/asciidoc/ja/Ch01_TermsOfUse.adoc[here(Japanese)] or link:/src/main/asciidoc/en/Ch01_TermsOfUse.adoc[here(English)].
