@startuml

start
  note
    Parallel Step Job
  end Note
  fork
    :Step1\nChunk Model;
  fork again
    :Step2\nTasklet Model\n(Chunk Transaction);
  fork again
    :Step3\nTasklet Model\n(Single Transaction);
  fork again
    :Step4\nChunk Model\n(Non-transactional Resource);
  end fork
stop

'Set styles such as format and color of each figure
skinparam Note {
  BackgroundColor #b1f8fa
  BorderColor black
}

skinparam Class {
  BorderColor black
  ArrowColor black
}

skinparam Activity {
  BorderColor black
  ArrowColor black
}

skinparam Sequence {
  BorderColor black
  ActorBorderColor black
  ArrowColor black
  LifeLineBorderColor black
  BoxLineColor black
  ParticipantBorderColor black
}

skinparam componentStyle uml2

skinparam Component {
  BorderColor black
  ArrowColor black
}

skinparam Interface {
  BorderColor black
  ArrowColor black
}

@enduml
