@startuml

artifact "Manager Step" as manager
database dbm [
master data
====
branch_id : 0001
....
branch_id : 0002
....
branch_id : 0003
....
branch_id : 0004
....
branch_id : 0005
....
branch_id : 0006
]

database db0 [
transaction data
====
]

frame "Thread Size = 4 (Worker Step active)" {
  artifact "Worker Step #4" as worker4
  artifact "Worker Step #3" as worker3
  artifact "Worker Step #2" as worker2
  artifact "Worker Step #1" as worker1

database db1 [
transaction data
====
branch_id : 0001
]

database db2 [
transaction data
====
branch_id : 0002
]

database db3 [
transaction data
====
branch_id : 0003
]

database db4 [
transaction data
====
branch_id : 0004
]

}

cloud  "Worker step waiting" #gray {
  artifact "Worker Step #6" as worker6 #lightgray
  artifact "Worker Step #5" as worker5 #lightgray
  database db5  #lightgray [
  transaction data
  ====
  branch_id : 0005
  ]
  database db6  #lightgray [
  transaction data
  ====
  branch_id : 0006
  ]

}

manager .up. dbm
manager .up. db0

manager -down-> worker1
manager -down-> worker2
manager -down-> worker3
manager -down-> worker4

manager ~down~ worker5 #white
manager ~down~ worker6 #white

worker1 ~down~ db1
worker2 ~down~ db2
worker3 ~down~ db3
worker4 ~down~ db4

worker5 ~down~ db5
worker6 ~down~ db6


'Set styles such as format and color of each figure
skinparam Note {
  BackgroundColor #b1f8fa
  BorderColor black
}

skinparam Class {
  BorderColor black
  ArrowColor black
}

skinparam Activity {
  BorderColor black
  ArrowColor black
}

skinparam Sequence {
  BorderColor black
  ActorBorderColor black
  ArrowColor black
  LifeLineBorderColor black
  BoxLineColor black
  ParticipantBorderColor black
}

skinparam componentStyle uml2

skinparam Component {
  BorderColor black
  ArrowColor black
}

skinparam Interface {
  BorderColor black
  ArrowColor black
}

@enduml
