@startuml

hide footbox
autonumber

participant Step
box "tasklet model" #lightblue
participant PointAddTasklet #Orange
participant MyBatisCursorItemReader
participant MyBatisBatchItemWriter
end box
database "member_info" as db

[->Step : execute()
activate Step
group Framework Transaction
    Step -> PointAddTasklet : execute()
    activate PointAddTasklet #Orange
    PointAddTasklet -> MyBatisCursorItemReader : open()
    activate MyBatisCursorItemReader
    MyBatisCursorItemReader -> db : select
    activate db
    loop until exhausted read data
        group Repeat until chunk size is reached
            PointAddTasklet -> MyBatisCursorItemReader : read()
            MyBatisCursorItemReader -> db : fetch
            db --> MyBatisCursorItemReader : result
            deactivate db
            MyBatisCursorItemReader --> PointAddTasklet : item
            deactivate MyBatisCursorItemReader
            PointAddTasklet -> PointAddTasklet : business logic
        end
        PointAddTasklet -> MyBatisBatchItemWriter : write(items)
        activate  MyBatisBatchItemWriter
        MyBatisBatchItemWriter -> db : update
        deactivate MyBatisBatchItemWriter
    end
    PointAddTasklet -> Step : FINISHED
    deactivate PointAddTasklet
Step [#blue]-> db : <font color="blue"><b>commit</b></font>
end
Step-->[ : ExitStatus
deactivate Step

'Set styles such as format and color of each figure
skinparam Note {
  BackgroundColor #b1f8fa
  BorderColor black
}

skinparam Class {
  BorderColor black
  ArrowColor black
}

skinparam Sequence {
  BorderColor black
  ActorBorderColor black
  ArrowColor black
  LifeLineBorderColor black
  BoxLineColor black
  ParticipantBorderColor black
}

skinparam componentStyle uml2

skinparam Component {
  BorderColor black
  ArrowColor black
}

skinparam Interface {
  BorderColor black
  ArrowColor black
}

@enduml
