@startuml

hide footbox
autonumber

participant Step
box "tasklet model" #lightblue
participant Tasklet
participant TransactionManager
participant Repository
end box
database "Resource" as db

[->Step : execute()
activate Step
group Framework Transaction (Resourceless)
    Step -> Tasklet : execute()
    activate Tasklet
    loop until exhausted read data
        group User Transaction
            Tasklet -> TransactionManager : beginTransaction()
            activate Repository
            activate TransactionManager
            loop until chunk size
                Tasklet -> Repository : find()
                Repository --> Tasklet : item
                Tasklet -> Tasklet : business logic
                activate Tasklet
                deactivate Tasklet
                Tasklet -> Repository : update(item)
                Repository -> db : update
            end
            Tasklet -> TransactionManager : commit()
            TransactionManager [#blue]-> db : <font color="blue"><b>commit</b></font>
            deactivate TransactionManager
            deactivate Repository
        end
    end
    Tasklet -> Step : FINISHED
    deactivate Tasklet
    Step -[#blue]>] : <font color="blue"><b>commit</b></font>
end
Step-->[ : ExitStatus
deactivate Step


'Set styles such as format and color of each figure
skinparam Note {
  BackgroundColor #b1f8fa
  BorderColor black
}

skinparam Class {
  BorderColor black
  ArrowColor black
}

skinparam Sequence {
  BorderColor black
  ActorBorderColor black
  ArrowColor black
  LifeLineBorderColor black
  BoxLineColor black
  ParticipantBorderColor black
}

skinparam componentStyle uml2

skinparam Component {
  BorderColor black
  ArrowColor black
}

skinparam Interface {
  BorderColor black
  ArrowColor black
}

@enduml
