@startsalt
{
{T
<&folder> asyncapp
+ <&folder> asyncapp-web
++ <&folder> src
+++ <&folder> main
++++ <&folder> java
+++++ <&folder> jp
++++++ <&folder> co
+++++++ <&folder> ntt
++++++++ <&folder> fw
+++++++++ <&folder> macchinetta
++++++++++ <&folder> batch
+++++++++++ <&folder> sample
++++++++++++ <&folder> config
+++++++++++++ <&folder> web
++++++++++++++ <&file> SpringSecurityConfig.java (1)
++++++++++++++ <&file> SpringMvcConfig.java (1)
++++++++++++++ <&file> SpringMvcRestConfig.java (2)
}
}
@endsalt
