@startuml

package "war" {
    package "asyncapp-web" {

      node "WebContext" {
        artifact [SpringMvcRestConfig.class (4)] as 4
      }
      node "WebRootContext" {
        artifact [ApplicationContextConfig.class (5)] as 5
      }
    }
    package "asyncbatch" {
      artifact [LaunchContextConfig.class (1)] as 1
      artifact [TerasolunaBatchConfiguration.class (6)] as 6
      node "JobContext" {
        artifact [JobBaseContextConfig.class (2)] as 2
        artifact [jobXxxConfig.class (3)] as 3
      }
    }
}

JobContext <- WebContext : modular
WebContext <- WebRootContext: modular
1 -> 6 : import
3 -> 2 : import
1 <- 4 : import

'Set styles such as format and color of each figure
skinparam componentStyle uml2

skinparam Component {
  BorderColor black
  ArrowColor black
  ArrowFontSize 18
}


@enduml
