@startuml

hide class circle
hide empty methods

class BATCH_JOB_INSTANCE {
  + JOB_INSTANCE_ID : BIGINT[20]
  VERSION : BIGINT[20]
  JOB_NAME : VARCHAR[100]
  JOB_KEY : VARCHAR[32]
}

class BATCH_JOB_EXECUTION {
  + JOB_EXECUTION_ID : BIGINT[20]
  VERSION : BIGINT[20]
  - JOB_INSTANCE_ID : BIGINT[20]
  CREATE_TIME : DATETIME
  START_TIME : DATETIME
  END_TIME : DATETIME
  STATUS : VARCHAR[10]
  EXIT_CODE : VARCHAR[100]
  EXIT_MESSAGE : VARCHAR[2500]
  LAST_UPDATE : DATETIME
}

class BATCH_JOB_EXECUTION_PARAMS {
  - JOB_EXECUTION_ID : BIGINT[20]
  TYPE_CD : VARCHAR[6]
  KEY_NAME : VARCHAR[100]
  STRING_VAL : VARCHAR[100]
  DATE_VAL : DATETIME
  LONG_VAL : BIGINT[20]
  DOUBLE_VAL : DOUBLE
  IDENTIFYING : CHAR[1]
}
class BATCH_JOB_EXECUTION_CONTEXT {
  - JOB_EXECUTION_ID : BIGINT[20]
  SHORT_CONTEXT : VARCHAR[2500]
  SERIALIZE_CONTEXT : TEXT
}

class BATCH_STEP_EXECUTION {
  + STEP_EXECUTION_ID : BIGINT[20]
  VERSION : BIGINT[20]
  STEP_NAME : VARCHAR[100]
  - JOB_EXECUTION_ID : BIGINT[20]
  START_TIME : DATETIME
  END_TIME : DATETIME
  STATUS : VARCHAR[10]
  COMMIT_COUNT : BIGINT[20]
  READ_COUNT : BIGINT[20]
  FILTER_COUNT : BIGINT[20]
  WRITE_COUNT : BIGINT[20]
  READ_SKIP_COUNT : BIGINT[20]
  WRITE_SKIP_COUNT : BIGINT[20]
  PROCESS_COUNT : BIGINT[20]
  ROLLBACK_COUNT : BIGINT[20]
  EXIT_CODE : VARCHAR[100]
  EXIT_MESSAGE : VARCHAR[2500]
  LAST_UPDATE : DATETIME
}

class BATCH_STEP_EXECUTION_CONTEXT {
  - STEP_EXECUTION_ID : BIGINT[20]
  SHORT_CONTEXT : VARCHAR[2500]
  SERIALIZE_CONTEXT : TEXT
}


BATCH_JOB_INSTANCE --o BATCH_JOB_EXECUTION
BATCH_JOB_EXECUTION -left-o BATCH_JOB_EXECUTION_PARAMS
BATCH_JOB_EXECUTION --o BATCH_JOB_EXECUTION_CONTEXT
BATCH_JOB_EXECUTION -right-o BATCH_STEP_EXECUTION
BATCH_STEP_EXECUTION --o BATCH_STEP_EXECUTION_CONTEXT

'Set styles such as format and color of each figure
skinparam Note {
  BackgroundColor #b1f8fa
  BorderColor black
}

skinparam Class {
  BorderColor black
  ArrowColor black
}

skinparam Sequence {
  BorderColor black
  ActorBorderColor black
  ArrowColor black
  LifeLineBorderColor black
  BoxLineColor black
  ParticipantBorderColor black
}

skinparam componentStyle uml2

skinparam Component {
  BorderColor black
  ArrowColor black
}

skinparam Interface {
  BorderColor black
  ArrowColor black
}

@enduml
