@startsalt
{
{T
<application-root>
+ <&folder> src
++ <&folder> main
+++ <&folder> java // (1)
++++ <&folder> com
+++++ <&folder> example
++++++ <&folder> batch
+++++++ <&folder> job01 // (6)
++++++++ <&file> Employee.java
++++++++ <&file> EmployeeProcessor.java
++++++++ <&file> EmployeeRepository.java
+++ <&folder> resources
++++ <&file> batch-application.properties // (7)
++++ <&file> logback.xml // (8)
++++ <&file> ValidationMessages.properties // (9)
++++ <&folder> com
+++++ <&folder> example
++++++ <&folder> batch
+++++++ <&folder> job01
++++++++ <&file> EmployeeRepository.xml // (10)
++++ <&folder> i18n
+++++ <&file> application-messages.properties // (11)
++++ <&folder> META-INF
+++++ <&folder> jobs // (12)
++++++ <&file> job01.xml
+++++ <&folder> spring // (2)
++++++ <&file> async-batch-daemon.xml // (3)
++++++ <&file> job-base-context.xml // (4)
++++++ <&file> launch-context.xml // (5)
++ <&folder> test
+++ <&folder> java
+++ <&folder> resources
}
}
@endsalt
