@startuml


artifact "Employee.class\n EmployeeProcessor.class\n EmployeeRepository.class\n  EmployeeRepository.xml" as 1
artifact "batch-application.properties" as 2
artifact "application-messages.properties" as 3
artifact "META-INF/jobs/job01.xml" as 4
artifact "async-batch-daemon.xml" as 5
artifact "job-base-context.xml" as 6
artifact "launch-context.xml" as 7

node "Job Sync Execution" as sync
node "Job ASync Execution" as async

4-up->6 : import always
6-up->7 : import at sync only
5-up->4 : load all files at start-up
5-up->7 : import
7-up->2 : load
7-up->3 : load
4-up->1 : use

sync-right->4 : load at start-up
async-right->5 :load at start-up

'Set styles such as format and color of each figure
skinparam componentStyle uml2

skinparam Component {
  BorderColor black
  ArrowColor black
  ArrowFontSize 24
}

@enduml
