@startsalt
{
{T
<application-root>
+ <&folder> src
++ <&folder> main
+++ <&folder> java // (1)
++++ <&folder> com
+++++ <&folder> example
++++++ <&folder> batch
+++++++ <&folder> config // (2)
++++++++ <&folder> helper
+++++++++ <&file> ApplicationContextFactoryHelper.java
++++++++ <&file> AsynBatchDaemonConfig.java // (3)
++++++++ <&file> JobBaseContextConfig.java // (4)
++++++++ <&file> LaunchContextConfig.java // (5)
++++++++ <&file> TerasolunaBatchConfiguration.java // (6)
+++++++ <&folder> job01 // (7)
++++++++ <&file> Employee.java
++++++++ <&file> EmployeeProcessor.java
++++++++ <&file> EmployeeRepository.java
+++++++ <&folder> jobs // (8)
++++++++ <&file> Job01Config.java
+++ <&folder> resources
++++ <&file> batch-application.properties // (9)
++++ <&file> logback.xml // (10)
++++ <&file> ValidationMessages.properties // (11)
++++ <&folder> com
+++++ <&folder> example
++++++ <&folder> batch
+++++++ <&folder> job01
++++++++ <&file> EmployeeRepository.xml // (12)
++++ <&folder> i18n
+++++ <&file> application-messages.properties // (13)
++ <&folder> test
+++ <&folder> java
+++ <&folder> resources
}
}
@endsalt
